# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4dbaa80ae69328447a8141a73b31774938f82b897cfaf8021812a2d32a8dbbcb8a8da25185cf04b9c179107446d1252ebfea4a8a9835f72d6795033ace09dd4

test:
  secret_key_base: a94d4c833f141543a37cb630675e48c2074f0c9df188ff832d4fdc7a4e00d0ef50c9c05afa260f7c3ae068edafa2f9f10259da239c7f6e2813fe65a1583be742

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
